# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Bundler:
  Enabled: true
Gemspec:
  Enabled: true
Layout:
  Enabled: true
Lint:
  Enabled: true
Metrics:
  Enabled: true
Naming:
  Enabled: true
Performance:
  Enabled: true
  Exclude:
    - "spec/**/*"
Rails:
  Enabled: true
Security:
  Enabled: true
Style:
  Enabled: true


Layout/IndentationWidth:
  Enabled: true

Style/Documentation:
  Enabled: false

# Layout/IndentationConsistency:
#   Enabled: true
#   EnforcedStyle: indented_internal_methods

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Enabled: false